# Generated by Django 5.2.1 on 2025-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
