# Generated by Django 5.2.1 on 2025-07-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0003_offrestage_duration_offrestage_remuneration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidature",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="internship",
        ),
        migrations.AddField(
            model_name="candidature",
            name="offre_stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appstage.offrestage",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="candidature",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appstage.candidature",
            ),
        ),
    ]
