# Generated by Django 5.2.1 on 2025-07-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0004_remove_candidature_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affectationstage",
            name="offer",
        ),
        migrations.AddField(
            model_name="affectationstage",
            name="offre_stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appstage.offrestage",
            ),
            preserve_default=False,
        ),
    ]
