# Generated by Django 5.2.1 on 2025-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstage', '0005_remove_affectationstage_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postnom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
