# Generated by Django 5.2.1 on 2025-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstage', '0006_user_postnom_user_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
