# Generated by Django 5.2.1 on 2025-07-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0008_subscriptionplan_companysubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
