# Generated by Django 5.2.1 on 2025-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0010_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysubscription",
            name="nbre_offres",
            field=models.IntegerField(default=0),
        ),
    ]
