# Generated by Django 5.2.1 on 2025-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0011_companysubscription_nbre_offres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysubscription",
            name="nbre_offres",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
