# Generated by Django 5.2.1 on 2025-08-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appstage", "0012_alter_companysubscription_nbre_offres"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysubscription",
            name="change_effective_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companysubscription",
            name="next_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="future_subscriptions",
                to="appstage.subscriptionplan",
            ),
        ),
    ]
