# Generated by Django 5.2.1 on 2025-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstage', '0013_companysubscription_change_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Totinda', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('homepage_banner', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('contact_email', models.EmailField(default='contact@totinda.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
